---

- block:
    - include_tasks: context.yml

    - include_tasks: context_service.yml

    - include_tasks: accounts.yml
      vars:
        accounts_groups: "{{ nginx_groups }}"
        accounts_users: "{{ nginx_users }}"

    - include_tasks: workspace.yml

    - include_tasks: install_packages.yml
      vars:
        packages: "{{ nginx_packages }}"
        services: "{{ nginx_services }}"

    - include_tasks: setup_nginx.yml

    - include_tasks: setup_nginx_sites.yml

    - include: service.yml

  when: want_nginx

- name: "set has_nginx to {{ want_nginx }}"
  set_fact:
    has_nginx: "{{ want_nginx }}"
